### ISSUE TITLE
`npm start` fails

### ISSUE THREAD

**Issue by ashleygwilliams** [ashleygwilliams/ashleygwilliams.github.io#19]
this might be an endpoints issue

```
> ashleygwilliams.github.io@0.2.0 start /Users/ag_dubs/Projects/ashleygwilliams.github.io
> node index.js

/Users/ag_dubs/Projects/ashleygwilliams.github.io/node_modules/endpoints/es5/application/lib/require_search.js:32
        throw result;
              ^
Error: No format specified.
    at Controller (/Users/ag_dubs/Projects/ashleygwilliams.github.io/node_modules/endpoints/es5/controller/index.js:54:13)
    at new Controller (/Users/ag_dubs/Projects/ashleygwilliams.github.io/node_modules/endpoints/es5/controller/index.js:83:14)
    at Object.<anonymous> (/Users/ag_dubs/Projects/ashleygwilliams.github.io/app/modules/community/controller.js:3:18)
```

**Comment by ftuyama** [comment]
# Workaround:
## Change endpoint version
On packages.json, use `"endpoints": "^0.6.0"`

## Specify format and store
On app/classes/api.js, specify `format` and `store`:
```
    format: Endpoints.Format.jsonapi,
    store: Endpoints.Store.bookshelf,
```
